name = "Tic-tac-toe"
description = "A simple application to run tic-tac-toe"



packages = ["pygame", "socket", "_thread", "sys", "math"]

[[fetch]]
files = ["./generic_tictactoe_client.py", "./generic_tictactoe_server.py", "./utils.py"]
