name = "Tic-tac-toe"
description = "A simple application to run tic-tac-toe"

[files]
"./generic_tictactoe_client.py" = ""
"./generic_tictactoe_server.py" = ""

packages = ["numpy", "matplotlib"]

[[fetch]]
files = ["./data.py"]
